config/routes.rb
Bukyokudb::Application.routes.draw do
  root to: 'courses#home'
  resources :courses, :only => [:show, :index]

end

app/models/course.rb
# encoding: UTF-8
class Course < ActiveRecord::Base
  attr_accessible :enrollment, :faculty, :name, :pass, :teacher
  paginates_per 100

  def percentage
    (pass.to_f / enrollment).round(3)
  end

  def rate
    case percentage
    when 0.8..1.0
      '神'
    when 0.0..0.5
      '鬼'
    else
      ''
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
# encoding: UTF-8
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.page params[:page]
    @courses = @courses.where('name LIKE ?', "%#{params[:name]}%") if params[:name]
    @courses = @courses.where('teacher LIKE ?', "%#{params[:teacher]}%") if params[:teacher]
    @courses = @courses.where('faculty LIKE ?', "%#{params[:faculty]}%") if params[:faculty]
    @courses = @courses.where('enrollment >= ?', params[:enrollment]) if params[:enrollment]
    @courses = params[:reversed] ? @courses.order('1.0 * pass / enrollment ASC') : @courses.order('1.0 * pass / enrollment DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teacher %><br />
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :faculty %><br />
    <%= f.text_field :faculty %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :enrollment %><br />
    <%= f.number_field :enrollment %>
  </div>
  <div class="field">
    <%= f.label :pass %><br />
    <%= f.number_field :pass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/home.html.erb
<%= link_to '京大神科目サーチ', courses_path %>

app/views/courses/index.html.erb
<h1><%= link_to '京大神科目サーチ', courses_path %></h1>
<p><%= link_to '各授業の平均学生在籍数', 'http://bukyokudb.iimc.kyoto-u.ac.jp/view/10-1' %>にある授業を単位取得率の高い順に表示します。何かあれば<%= link_to '@uiureo', 'https://twitter.com/uiureo' %>まで </p>

<a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja">ツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<p>
<%= link_to '鬼科目（履修者100人以上）', courses_path(enrollment: 100, reversed: true) %>
<%= link_to '一般教養神科目（履修者100人以上）', courses_path(faculty: '高等教育研究開発推進機構', enrollment: 100) %>
<%= link_to '一般教養鬼科目（履修者100人以上）', courses_path(faculty: '高等教育研究開発推進機構', enrollment: 100) %>
<%= link_to '英語神科目', courses_path(name: '英語') %>
</p>

<hr />

<%= form_tag courses_path, :method => :get do %>
  <%= label_tag 'teacher', '教員名' %>
  <%= text_field_tag 'teacher', params[:teacher] %>

  <%= label_tag 'name', '授業名' %>
  <%= text_field_tag 'name', params[:name] %>

  <%= label_tag 'faculty', '開講部局' %>
  <%= text_field_tag 'faculty', params[:faculty] %>

  <%= label_tag 'enrollment', '登録者数以上' %>
  <%= number_field_tag 'enrollment', params[:enrollment] || 0, min: 0 %>

  <%= label_tag 'reversed', '鬼科目順にする' %>
  <%= check_box_tag 'reversed', true, params[:reversed] %>

  <%= submit_tag '検索', name: nil %>
<% end %>

<table>
  <tr>
    <th>教員名</th>
    <th>開講部局</th>
    <th>授業科目名</th>
    <th>履修登録者数</th>
    <th>単位取得者数</th>
    <th>単位取得率</th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.teacher %></td>
    <td><%= course.faculty %></td>
    <td><%= course.name %></td>
    <td><%= course.enrollment %></td>
    <td><%= course.pass %></td>
    <td><%= course.percentage %></td>
    <td><%= link_to '表示', course %></td>
  </tr>
<% end %>
</table>

<%= paginate @courses %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<%= content_for(:title){ "#{@course.name} (#{@course.teacher})" } %>

<p>
  <b>教師名:</b>
  <%= @course.teacher %>
</p>

<p>
  <b>開講部局:</b>
  <%= @course.faculty %>
</p>

<p>
  <b>授業科目名:</b>
  <%= @course.name %>
</p>

<p>
  <b>履修登録者数:</b>
  <%= @course.enrollment %>
</p>

<p>
  <b>単位取得者数:</b>
  <%= @course.pass %>
</p>

<p>
  <b>単位取得率:</b>
  <h2><%= "#{(@course.percentage * 100).to_i}%" %></h2>
</p>

<%= link_to '戻る', courses_path %>

<br/>
<br/>

<a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja">ツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) + '- 京大神科目サーチ' : '京大神科目サーチ' %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>